// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "ozon_entrance/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// LinksRepository is an autogenerated mock type for the LinksRepository type
type LinksRepository struct {
	mock.Mock
}

// GetLink provides a mock function with given fields: ctx, shortLink
func (_m *LinksRepository) GetLink(ctx context.Context, shortLink string) (entities.Link, error) {
	ret := _m.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 entities.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Link, error)); ok {
		return rf(ctx, shortLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Link); ok {
		r0 = rf(ctx, shortLink)
	} else {
		r0 = ret.Get(0).(entities.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveLink provides a mock function with given fields: ctx, originalLink, shortUrl
func (_m *LinksRepository) SaveLink(ctx context.Context, originalLink string, shortUrl string) (entities.Link, error) {
	ret := _m.Called(ctx, originalLink, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for SaveLink")
	}

	var r0 entities.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entities.Link, error)); ok {
		return rf(ctx, originalLink, shortUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entities.Link); ok {
		r0 = rf(ctx, originalLink, shortUrl)
	} else {
		r0 = ret.Get(0).(entities.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, originalLink, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinksRepository creates a new instance of LinksRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinksRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinksRepository {
	mock := &LinksRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
