// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "ozon_entrance/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// LinksUseCase is an autogenerated mock type for the LinksUseCase type
type LinksUseCase struct {
	mock.Mock
}

// CreateLink provides a mock function with given fields: ctx, originalLink
func (_m *LinksUseCase) CreateLink(ctx context.Context, originalLink dto.OriginalLink) (*dto.ShortLink, error) {
	ret := _m.Called(ctx, originalLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 *dto.ShortLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.OriginalLink) (*dto.ShortLink, error)); ok {
		return rf(ctx, originalLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.OriginalLink) *dto.ShortLink); ok {
		r0 = rf(ctx, originalLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ShortLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.OriginalLink) error); ok {
		r1 = rf(ctx, originalLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLink provides a mock function with given fields: ctx, shortLink
func (_m *LinksUseCase) GetLink(ctx context.Context, shortLink string) (*dto.OriginalLink, error) {
	ret := _m.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 *dto.OriginalLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.OriginalLink, error)); ok {
		return rf(ctx, shortLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.OriginalLink); ok {
		r0 = rf(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OriginalLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinksUseCase creates a new instance of LinksUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinksUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinksUseCase {
	mock := &LinksUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
