// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShortLinkGenerator is an autogenerated mock type for the ShortLinkGenerator type
type ShortLinkGenerator struct {
	mock.Mock
}

// GenerateShortLink provides a mock function with no fields
func (_m *ShortLinkGenerator) GenerateShortLink() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateShortLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortLinkGenerator creates a new instance of ShortLinkGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortLinkGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortLinkGenerator {
	mock := &ShortLinkGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
